version = "1.0"

[main]
name = "Element configuration"

    [main.config]
    name = "Server Configuration"

        [main.config.default_home_server]
        ask = "Choose a home server"
        type = "string"
        default = "matrix.org"
        bind = ":__FINALPATH__/config.json"

        [main.config.enable_labs]
        ask = "Enable labs settings"
        type = "boolean"
        bind = "showLabsSettings:__FINALPATH__/config.json"

        [main.config.default_theme]
        ask = "Choose a theme"
        type = "select"
        choices = ["light", "dark"]
        bind = ":__FINALPATH__/config.json"
