version = "1.0"

[main]
name = "Element configuration"

    [main.config]
    name = "Home server Configuration"

        [main.config.default_home_server]
        ask = "Choose a default home server"
        type = "string"
        default = "matrix.org"
        bind = "default_hs_url:__FINALPATH__/config.json"
