version = "1.0"

[main]
name = "Element configuration"

    [main.config]
    name = "Server Configuration"

        [main.config.default_home_server]
        ask = "Choose a home server"
        type = "domain"
        default = "https://matrix-client.matrix.org"
        pattern.regexp = '^https://'
        bind = "base_url:__FINALPATH__/config.json"
