version = "1.0"

[main]
name = "Element configuration"

    [main.config]
    name = "Server Configuration"

        [main.config.default_home_server]
        ask = "Choose a home server"
        type = "domain"
        default = ""
        bind = "default_server_name:__FINALPATH__/config.json"
