version = "1.0"

[main]
name = "Element configuration"

    [main.config]
    name = "Server Configuration"

        [main.config.default_home_server]
        ask = "Choose a home server"
        type = "url"
        default = "https://matrix-client.matrix.org"
        bind = ":__FINALPATH__/config.json"
