#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Stop script if errors
ynh_abort_if_errors

# Import common cmd
source ../settings/scripts/experimental_helper.sh
source ../settings/scripts/_common.sh

#=================================================
# STANDARD BACKUP STEPS
#=================================================

# Retrieve arguments
ynh_script_progression --message="Loading installation settings..."
domain=$(ynh_app_setting_get --app $app --key domain)

ynh_script_progression --message="Backing configuration..."

# Copy Nginx config
ynh_backup --src_path "/etc/nginx/conf.d/${domain}.d/${app}.conf" "nginx.conf"

# BACKUP THE PHP-FPM CONFIGURATION
ynh_backup --src_path "/etc/php5/fpm/pool.d/$app.conf"

# Backup riot files
ynh_script_progression --message="Backing up the main app directory..."
ynh_backup --src_path "/var/www/$app"
