#!/bin/bash

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Import common cmd
source ./_common.sh

# Retrive arguments
old_domain=$YNH_APP_OLD_DOMAIN
old_path=$(ynh_normalize_url_path $YNH_APP_OLD_PATH)
new_domain=$YNH_APP_NEW_DOMAIN
new_path=$(ynh_normalize_url_path $YNH_APP_NEW_PATH)

# CHECK WHICH PARTS SHOULD BE CHANGED
change_domain=0
if [ "$old_domain" != "$new_domain" ]
then
	change_domain=1
fi

change_path=0
if [ "$old_path" != "$new_path" ]
then
	change_path=1
fi

# STANDARD MODIFICATIONS
# MODIFY URL IN NGINX CONF
nginx_conf_path=/etc/nginx/conf.d/$old_domain.d/$app.conf

# Change the path in the nginx config file
if [ $change_path -eq 1 ]
then
	ynh_replace_string "location $old_path" "location $new_path" "$nginx_conf_path"
fi

# Change the domain for nginx
if [ $change_domain -eq 1 ]
then
	sudo mv $nginx_conf_path /etc/nginx/conf.d/$new_domain.d/$app.conf
fi

# Reload services
sudo systemctl reload nginx.service