#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Stop script if errors
ynh_abort_if_errors

# Import common cmd
source ./_common.sh

# Retrive arguments
old_domain=$YNH_APP_OLD_DOMAIN
old_path=$YNH_APP_OLD_PATH

new_domain=$YNH_APP_NEW_DOMAIN
new_path=$YNH_APP_NEW_PATH

test -n "$old_path" || old_path="/"
test -n "$new_path" || new_path="/"

new_path=$(ynh_normalize_url_path $new_path)
old_path=$(ynh_normalize_url_path $old_path)

# CHECK WHICH PARTS SHOULD BE CHANGED
change_domain=0
if [ "$old_domain" != "$new_domain" ]
then
	change_domain=1
fi

change_path=0
if [ "$old_path" != "$new_path" ]
then
	change_path=1
fi

# STANDARD MODIFICATIONS
# MODIFY URL IN NGINX CONF
nginx_conf_path=/etc/nginx/conf.d/$old_domain.d/$app.conf

# Change the path in the nginx config file
if [ $change_path -eq 1 ]
then
    # Make a backup of the original nginx config file if modified
    ynh_backup_if_checksum_is_different "$nginx_conf_path"
    # Replace locations starting with old_path
    # Look for every location possible patterns (see https://nginx.org/en/docs/http/ngx_http_core_module.html#location)

    # Move from sub path to root
    if [ "$new_path" == "/" ]
    then
        ynh_replace_string "location\( \(=\|~\|~\*\|\^~\)\)\? $old_path/\?" "location\1 /"  "$nginx_conf_path"
        ynh_replace_string "\(^.*rewrite.*\^$old_path.* permanent;\)" "#sub_path_only\1" "$nginx_conf_path"
        ynh_replace_string "\(rewrite *\^\)$old_path\$ $old_path/*" "\1$new_path$ $new_path" "$nginx_conf_path"

    # Move to a sub path
    else
        ynh_replace_string "location\( \(=\|~\|~\*\|\^~\)\)\? $old_path/\?" "location\1 $new_path/"  "$nginx_conf_path"
        ynh_replace_string "^#sub_path_only" "" "$nginx_conf_path"
        ynh_replace_string "\(rewrite *\^\)$old_path\$ $old_path/*" "\1$new_path$ $new_path/" "$nginx_conf_path"
    fi
    
    # Calculate and store the nginx config file checksum
    ynh_store_file_checksum "$nginx_conf_path"
fi

# Change the domain for nginx
if [ $change_domain -eq 1 ]
then
	sudo mv $nginx_conf_path /etc/nginx/conf.d/$new_domain.d/$app.conf
fi

# Reload services
sudo systemctl reload nginx.service