#!/bin/bash

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Stop script if errors
ynh_abort_if_errors

# Import common cmd
source ./_common.sh

# Retrieve arguments
domain=$YNH_APP_ARG_DOMAIN
path_url=$(ynh_normalize_url_path $YNH_APP_ARG_PATH)
is_public=$YNH_APP_ARG_IS_PUBLIC
default_home_server=$YNH_APP_ARG_DEFAULT_HOME_SERVER

# Check domain/path availability
ynh_webpath_available $domain $path_url || ynh_die "$domain$path_url is not available, please use an other domain or path."
ynh_webpath_register $app $domain $path_url

# Check Final Path availability
test ! -e "$final_path" || ynh_die "This path already contains a folder"

# Enregistre les infos dans la config YunoHost
ynh_app_setting_set $app is_public $is_public
ynh_app_setting_set $app default_home_server $default_home_server
ynh_app_setting_set $app final_path $final_path

# Get source and install in source dir
install_source

# Create a system user
ynh_system_user_create $app

# Create a dedicated php-fpm config
ynh_add_fpm_config

# Update Riot config
config_riot

# Config nginx
config_nginx

# Set final permission
set_permission

if [ "$is_public" = "0" ];
then	# Retire l'accès public
	ynh_app_setting_delete $app skipped_uris
else
    ynh_app_setting_set $app skipped_uris "/"
fi

# Recharge la configuration Nginx
systemctl reload nginx.service
