#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# Import common cmd
source ./experimental_helper.sh
source ./_common.sh

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Stop script if errors
ynh_abort_if_errors

ynh_script_progression --message="Validating installation parameters..."

# Retrieve arguments
domain=$YNH_APP_ARG_DOMAIN
path_url=$(ynh_normalize_url_path --path_url $YNH_APP_ARG_PATH)
is_public=$YNH_APP_ARG_IS_PUBLIC
default_home_server=$YNH_APP_ARG_DEFAULT_HOME_SERVER

# Register (book) web path
ynh_webpath_register --app $app --domain $domain --path_url $path_url

# Check Final Path availability
test ! -e "$final_path" || ynh_die --message "This path already contains a folder"

# Enregistre les infos dans la config YunoHost
ynh_script_progression --message="Storing installation settings..."
ynh_app_setting_set --app $app --key is_public --value $is_public
ynh_app_setting_set --app $app --key default_home_server --value $default_home_server
ynh_app_setting_set --app $app --key final_path --value $final_path

#=================================================
# STANDARD MODIFICATIONS
#=================================================

# Get source and install in source dir
ynh_script_progression --message="Installing sources files..." --weight=10
install_source

# Update Element config
config_element

# Config nginx
ynh_add_nginx_config

#=================================================
# GENERIC FINALIZATION
#=================================================

# Set final permission
ynh_script_progression --message="Protecting directory"
set_permission

ynh_script_progression --message="Configuring permissions"
if [ "$is_public" == '1' ];
then
    ynh_permission_update --permission "main" --add "visitors"
fi

# Recharge la configuration Nginx
systemctl reload nginx.service

ynh_script_progression --message="Installation of $app completed" --last
