#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# Import common cmd
source ./experimental_helper.sh
source ./_common.sh

# Source YunoHost helpers
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================

# Retrieve arguments
ynh_script_progression --message="Loading installation settings..."
domain=$(ynh_app_setting_get --app $app --key domain)

# Remove all files
ynh_script_progression --message="Removing app main directory..." --weight=4
ynh_secure_remove --file="/var/www/$app"

# Suppression de la configuration nginx
ynh_script_progression --message="Removing configuration..."
ynh_remove_nginx_config

ynh_script_progression --message="Removal of $app completed" --last
