#!/bin/bash

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Stop script if errors
set -u

# Import common cmd
source ./_common.sh

# Retrieve arguments
domain=$(ynh_app_setting_get $app domain)

ynh_secure_remove "/var/www/$app"

# Suppression de la configuration nginx
ynh_secure_remove "/etc/nginx/conf.d/$domain.d/$app.conf"
systemctl reload nginx.service

