#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Import common cmd
source ./_common.sh

#=================================================
# STANDARD REMOVE
#=================================================

# Retrieve arguments
domain=$(ynh_app_setting_get $app domain)

ynh_secure_remove "/var/www/$app"

# Remove the dedicated php-fpm config
ynh_remove_fpm_config

# Delete a system user
ynh_system_user_delete $app

# Suppression de la configuration nginx
ynh_remove_nginx_config
