#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Stop script if errors
ynh_abort_if_errors

# Import common cmd
source ../settings/scripts/_common.sh

# Retrieve arguments
domain=$(ynh_app_setting_get $app domain)
path_url=$(ynh_app_setting_get $app path)

# Check domain/path availability
ynh_webpath_available $domain $path_url || ynh_die "$domain/$path_url is not available, please use an other domain or path."

#=================================================
# STANDARD RESTORATION STEPS
#=================================================

# Create a system user
ynh_system_user_create $app

# Restore all config and data
ynh_restore

#=================================================
# GENERIC FINALIZATION
#=================================================

# Set final permission
set_permission

# Reload nginx
systemctl reload nginx.service
systemctl reload php5-fpm