#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Stop script if errors
ynh_abort_if_errors

# Import common cmd
source ../settings/scripts/experimental_helper.sh
source ../settings/scripts/_common.sh

# Retrieve arguments
ynh_script_progression --message="Loading settings..."
domain=$(ynh_app_setting_get --app $app --key domain)
path_url=$(ynh_app_setting_get --app $app --key path)

# Check domain/path availability
ynh_webpath_available --domain $domain --path_url $path_url || ynh_die --message "$domain/$path_url is not available, please use an other domain or path."

#=================================================
# STANDARD RESTORATION STEPS
#=================================================

# Create a system user
ynh_script_progression --message="Recreating the dedicated system user..."
ynh_system_user_create --username $app

# Restore all config and data
ynh_script_progression --message="Restoring files..." --weight=10
ynh_restore

#=================================================
# GENERIC FINALIZATION
#=================================================

# Set final permission
ynh_script_progression --message="Protecting directory..."
set_permission

# Reload nginx
ynh_script_progression --message="Reloading services..."
systemctl reload nginx.service
systemctl reload php5-fpm
