#!/bin/bash

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Stop script if errors
ynh_abort_if_errors

# Import common cmd
source ./_common.sh

# Retrieve arguments
domain=$(ynh_app_setting_get $app domain)
path_url=$(ynh_normalize_url_path $(ynh_app_setting_get $app path))
is_public=$(ynh_app_setting_get $app is_public)
final_path=$(ynh_app_setting_get $app final_path)
default_home_server=$(ynh_app_setting_get $app default_home_server)

# Get source and install in source dir
ynh_setup_source $final_path/
chown www-data -R $final_path
chmod 740 -R $final_path

# Update nginx config
config_nginx

# Update Riot config
config_riot

# Recharge la configuration Nginx
systemctl reload nginx.service
